---
env_config:
  layout: |
    XXXXXXX
    XADDDDX
    XDDDDDX
    XDDDDDX
    XDDDDDX
    XDDDDAX
    XXXXXXX
  tick_limit: 12

model_config:
  num_hidden_layers:
  size_hidden_layers:
  num_filters:
  num_conv_layers:

ray_config:
  framework: torch
  env: "ZSC-Cleaner"
  num_workers: 10
  train_batch_size: 2000
  rollout_fragment_length: 100
  vf_loss_coef: 0.01
  lr: 0.001
  seed: 0

policy_config:
  0: dqn
  1: dqn

run_config:
  verbose: True
  wandb_project: zsc-cleaner
