---
env_config:
  layout: |
      XXXXX
      XADDX
      XDDDX
      XDDAX
      XXXXX
  tick_limit: 50
  num_agents: 2

model_config:
  num_hidden_layers:
  size_hidden_layers:
  num_filters:
  num_conv_layers:

ray_config:
  framework: torch
  env: "ZSC-Cleaner"
  num_workers: 10
  train_batch_size: 400
  rollout_fragment_length: 100
  lr: 0.0001
  evaluation_interval: 5
  evaluation_num_episodes: 5
  evaluation_num_workers: 0
  seed: 0

policy_config:
  0: dqn
  1: dqn

run_config:
  verbose: True
  wandb_project: zsc-cleaner