---
env_config:
  layout: |
      XXXXX
      XADDX
      XDDDX
      XDDAX
      XXXXX

model_config:
  num_hidden_layers:
  size_hidden_layers:
  num_filters:
  num_conv_layers:

ray_config:
  framework: torch
  env: "ZSC-Cleaner"
  train_batch_size: 400
  rollout_fragment_length: 200
  lr: 0.001
  evaluation_interval: 25
  evaluation_num_episodes: 5
  seed: 0

policy_config:
  0: dqn
  1: dqn

run_config:
  verbose: True