---
env_config:
  layout: |
      XXXXX
      XADDX
      XDDDX
      XDDAX
      XXXXX

model_config:
  num_hidden_layers:
  size_hidden_layers:
  num_filters:
  num_conv_layers:

ray_config:
  framework: torch
  env: "ZSC-Cleaner"
  train_batch_size: 400
  rollout_fragment_length: 200
  sgd_minibatch_size: 512
  num_sgd_iter: 3
  lambda: 0.92
  kl_coeff: 0.2
  lr: 1e-3
  vf_loss_coeff: 1.0e-2
  gamma: 0.99
  evaluation_interval: 25
  evaluation_num_episodes: 5
  seed: 0

policy_config:
  0: dqn
  1: dqn

run_config:
  verbose: True