---
env_config:
  layout: |
    XXXXXXXXXXXXX
    XADDDDDDDDDDX
    XDDDDDDDDDDDX
    XDDDDDDDDDDDX
    XDDDDDDDDDDDX
    XDDDDDDDDDDDX
    XDDDDDDDDDDDX
    XDDDDDDDDDDDX
    XDDDDDDDDDDDX
    XDDDDDDDDDDDX
    XDDDDDDDDDDDX
    XDDDDDDDDDDAX
    XXXXXXXXXXXXX
  tick_limit: 100
  num_agents: 2
  time_penalty: -0.25
  clean_penalty: 0.0

model_config:
  conv_kernel_size: 3

ray_config:
  framework: torch
  env: "ZSC-Cleaner"
  num_workers: 10
  train_batch_size: 1000
  rollout_fragment_length: 100
  lr: 0.0001

run_config:
  wandb_project: zsc-cleaner
  verbose: True
