---
env_config:
  layout: |
      XXXXXXXXXXXX
      XADDDDDDDDDX
      XDDDDDDDDDDX
      XDDDDDDDDDDX
      XDDDDDDDDDDX
      XDDDDDDDDDDX
      XDDDDDDDDDDX
      XDDDDDDDDDDX
      XDDDDDDDDDDX
      XDDDDDDDDDDX
      XDDDDDDDDDAX
      XXXXXXXXXXXX
  tick_limit: 50
  num_agents: 2

model_config:
  num_hidden_layers:
  size_hidden_layers:
  num_filters:
  num_conv_layers:

ray_config:
  framework: torch
  env: "ZSC-Cleaner"
  num_workers: 10
  train_batch_size: 2000
  rollout_fragment_length: 100
  lr: 0.001
  seed: 0

run_config:
  verbose: True
  wandb_project: zsc-cleaner
